### ISSUE TITLE
Figure out how to set the HAVE_ macros when using YARP in JRuby & TruffleRuby

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1041]
See https://github.com/ruby/yarp/pull/979#issuecomment-1602495850
cc @enebo

**Comment by kddnewton** [comment]
I think this is going to be very much dependent on how you build it in your repository, but you can set them via the `-DHAVE_*` flags for C compilers. I'm not sure if there's anything to be done on the YARP side here.

**Comment by eregon** [comment]
I found a way, by reusing YARP's Makefile and the static library it generates: https://github.com/ruby/yarp/pull/1051#issuecomment-1613115237
