### ISSUE TITLE
Incorrect symbol resolution

### ISSUE THREAD

**Issue by kddnewton** [ruby/yarp#1067]
Right now when you use Ruby's master branch, it's always resolving `yp_parse` to the one found in Ruby, and not the one found in YARP. This means our CI is now starting to fail because when we push changes it uses the old one to test and fails. We need to change our linking to favor our own symbols over the ones found in Ruby.

**Comment by flavorjones** [comment]
Taking a look this morning, and I'm realizing (remembering) that `-load_hidden` is not available on linux (it's a mach-o/darwin feature). So I'm going to explore a couple of other ideas.

**Comment by flavorjones** [comment]
PR at #1069.
