### ISSUE TITLE
Hang parsing malformed heredoc

### ISSUE THREAD

**Issue by stevenjohnstone** [ruby/yarp#1075]
Demo
```C
#include <yarp.h>

unsigned char hang[] = {
  '<', '<', '"', '"', '*', '<', '<', '"', '"', '\\', '\n', '\n',
  '\n', '*', '<', '<', '"', '\\'
};


int main(int argc, const char **argv) {
  yp_buffer_t *buffer = malloc(sizeof(yp_buffer_t));
  yp_buffer_init(buffer);
  yp_parse_serialize((const char *)hang, sizeof(hang) - 1, buffer);
  yp_buffer_free(buffer);
  free(buffer);
  return 0;
}
```
Running this will result in an infinite loop calling malloc repeatedly. Here's where it spends its time:

![graph](https://github.com/ruby/yarp/assets/6546704/754c0337-7425-45ce-8f4b-49b9fd0f7357)

Note that the trailing backslash in the input is beyond the range passed to ```yp_parse_serialize``` so hitting this bug depends on the memory environment making it hard to debug.

Tested on f59c3758546b608bd5318c5a91660e46d3490fdf.

**Comment by kddnewton** [comment]
Also fixed by #1082
