### ISSUE TITLE
Use the constant pool for strings not necessirely as-is in the source (e.g. for CallNode#name)

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1134]
For things like `a.foo(2, 3)` it seems great to use the constant pool.
But I guess it can't for `a.foo = 42` (there is no `foo=` in that source).

If the constant pool wasn't based on offsets in the source it wouldn't be a problem though, so maybe the constant pool should just own the strings it points to, and serialize them as well.
This could also result in a speedup while deserializing, due to all constant pool strings being next to each in memory, vs spread in the source.
And it would help to remove the need to access the source while deserializing (related-ish: #807)

Not a blocker or anything, but it could be a nice optimization for deserialization speed, at the cost of some serialized size though (but removing the need to keep the source as a byte[]/char* around).

**Comment by enebo** [comment]
@eregon I think so but then I think a requirement for us should be that we should not need to hold onto original Ruby source to process serialized code (it is a big memory requirement right now).  That would mean names could be in the serialized node but then it makes more sense to just keep them in a constant pool since many names are repeated in a source file.

**Comment by eregon** [comment]
One thought about this: currently after Loader is done, the constant pool is fully resolved, so we don't need to keep the source around after Loader is done. So the constant pool could be a hybrid of owned strings and (start, length) in source.

**Comment by kddnewton** [comment]
We support this now. We don't support it for `CallNode#name`, but I'm going to close this in favor of #1296, which indicates that.

**Comment by eregon** [comment]
OK, I moved that part of #1296 to #1530
