### ISSUE TITLE
Adding ConstantWriteNode?

### ISSUE THREAD

**Issue by andrykonchin** [ruby/yarp#1136]
It seems consistent to have a `ConstantWriteNode` node for constants without outer lexical scope name (e.g. "A = 1").

Currently constant assigning is expressed with `ConstantPathWriteNode` for both cases - with and without prefix:

```
bin/parse -e 'FOO = 1'
#<YARP::ParseResult:0x000000010b7177b0
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x000000010e1fedc0 @offsets=[0], @source="FOO = 1">,
 @value=ProgramNode(0...7)([], StatementsNode(0...7)([ConstantPathWriteNode(0...7)(ConstantReadNode(0...3)(), (4...5), IntegerNode(6...7)())])),
 @warnings=[]>
```

```
bin/parse -e 'FOO::BAR = 1'
#<YARP::ParseResult:0x0000000104562d68
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x000000010463eb10 @offsets=[0], @source="FOO::BAR = 1">,
 @value=
  ProgramNode(0...12)(
    [],
    StatementsNode(0...12)(
      [ConstantPathWriteNode(0...12)(ConstantPathNode(0...8)(ConstantReadNode(0...3)(), ConstantReadNode(5...8)(), (3...5)), (9...10), IntegerNode(11...12)())]
    )
  ),
 @warnings=[]>
```

It's inconsistent with constant reading that could be expressed with `ConstantReadNode` and `ConstantPathNode`.

Additionally, `ConstantWriteNode` has one extra node for the most common case (IMHO, when there is no prefix) in comparison to proposed `ConstantWriteNode`.

**Comment by jemmaissroff** [comment]
➕ This makes a lot of sense to me. I thought something similar when working on the CRuby interpreter
