### ISSUE TITLE
Add ephemeral CallNode arguments for attribute and element reference assignment

### ISSUE THREAD

**Issue by andrykonchin** [ruby/yarp#1143]
In some cases a method call may not have explicit arguments but they will be provided by runtime. It will be helpful to have placeholder nodes for such _missing_ arguments - either NilNode or something similar to MissingNode.

Examples of such calls:

## Attribute assignment

Ruby code:

```ruby
begin
rescue => a.foo
end
```

AST:

```
#<YARP::ParseResult:0x0000000106557588
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x000000010903ee40 @offsets=[0, 6, 22, 26], @source="begin\n" + "rescue => a.foo\n" + "end\n">,
 @value=
  ProgramNode(0...25)(
    [],
    StatementsNode(0...25)(
      [BeginNode(0...25)(
         (0...5),
         nil,
         RescueNode(6...12)(
           (6...12),
           [],
           (13...15),
           CallNode(16...21)(CallNode(16...17)(nil, nil, (16...17), nil, nil, nil, nil, 0, "a"), (17...18), (18...21), nil, nil, nil, nil, 0, "foo="),
           nil,
           nil
         ),
         nil,
         nil,
         (22...25)
       )]
    )
  ),
 @warnings=[]>
```

A CallNode for `foo=` has no attributes at all currently. But actual call will have one argument - assigned value.

## Element reference assignment

Ruby code:

```ruby
begin
rescue => h[:foo]
end
```

AST:

```
#<YARP::ParseResult:0x0000000109802be0
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00000001098deb68 @offsets=[0, 6, 24, 28], @source="begin\n" + "rescue => h[:foo]\n" + "end\n">,
 @value=
  ProgramNode(0...27)(
    [],
    StatementsNode(0...27)(
      [BeginNode(0...27)(
         (0...5),
         nil,
         RescueNode(6...12)(
           (6...12),
           [],
           (13...15),
           CallNode(16...23)(
             CallNode(16...17)(nil, nil, (16...17), nil, nil, nil, nil, 0, "h"),
             nil,
             (17...23),
             (17...18),
             ArgumentsNode(18...22)([SymbolNode(18...22)((18...19), (19...22), nil, "foo")]),
             (22...23),
             nil,
             0,
             "[]="
           ),
           nil,
           nil
         ),
         nil,
         nil,
         (24...27)
       )]
    )
  ),
 @warnings=[]>
```

A CallNode for `[]=` method call has only one argument `foo`, but actual call will have the second argument - assigned value.

**Comment by eregon** [comment]
Notably this seems important so the arity of the call can be computed correctly, the current situation yields incorrect arity and number of arguments, so any semantic processing the YARP AST there is basically broken unless it manually works around this bug.

**Comment by kddnewton** [comment]
Is the rescue target the only place you're talking about? I can't really find any other places in the AST where this might be used.

It looks like there are various approaches to this. ripper and parser have nothing. ruby_parser has `s(:gvar, :$!)` (but this seems not right since it's a special local var). CRuby has a special `NODE_ERRINFO` node type.

I think I'd like to add `$!` to the local table and make this a local variable read as that seems the most correct.

**Comment by andrykonchin** [comment]
> Is the rescue target the only place you're talking about?

Another case could be multi-assignment:

```ruby
a.foo, b = [1, 2]
```

The `a.foo=` method call has no arguments node:

```
#<YARP::ParseResult:0x0000000108a57540
 @comments=
  [#<YARP::Comment:0x000000010b52e868 @location=(0...7), @type=:inline>,
   #<YARP::Comment:0x000000010b52e7f0 @location=(7...27), @type=:inline>,
   #<YARP::Comment:0x000000010b52e7a0 @location=(20...46), @type=:inline>,
   #<YARP::Comment:0x000000010b52e750 @location=(26...57), @type=:inline>],
 @errors=[],
 @source=
  #<YARP::Source:0x000000010b52eea8 @offsets=[0, 7, 20, 26, 31, 32, 50], @source="#begin\n" + "#rescue => a\n" + "#  42\n" + "#end\n" + "\n" + "a.foo, b = [1, 2]\n">,
 @value=
  ProgramNode(32...49)(
    [:b],
    StatementsNode(32...49)(
      [MultiWriteNode(32...49)(
         [CallNode(32...37)(CallNode(32...33)(nil, nil, (32...33), nil, nil, nil, nil, 0, "a"), (33...34), (34...37), nil, nil, nil, nil, 0, "foo="),
          LocalVariableWriteNode(39...40)(:b, 0, nil, (39...40), nil)],
         (41...42),
         ArrayNode(43...49)([IntegerNode(44...45)(), IntegerNode(47...48)()], (43...44), (48...49)),
         nil,
         nil
       )]
    )
  ),
 @warnings=[]>
```

**Comment by eregon** [comment]
Right, that multiple assignment example why I think a "missing node" or some kind of placeholder would be best there.
And then we can also use this when compiling to assert it's indeed a placeholder node and we should pass the value directly instead of trying to execute or compile that node.

> I think I'd like to add `$!` to the local table and make this a local variable read as that seems the most correct.

`$!` is thread-local so that wouldn't be correct.

**Comment by eregon** [comment]
The JRuby AST uses `NilImplicitNode` for such a case (which is different than `NilNode` in that it's implicit/synthetic/no location).

The parser gem indeed gives the incorrect arity as if there was no value argument:
```
ruby -rparser/current -e 'pp Parser::CurrentRuby.parse("a.foo, b = [1, 2]")'                                
s(:masgn,
  s(:mlhs,
    s(:send,
      s(:send, nil, :a), :foo=),
    s(:lvasgn, :b)),
  s(:array,
    s(:int, 1),
    s(:int, 2)))
```
Maybe the `mlhs` is a sort of marker to somehow carry that information, but it seems inconvenient.

**Comment by eregon** [comment]
I got a bit curious what happen for rubocop-ast for that case: the value node is `nil`:
```
$ ruby -rrubocop/ast -e 'pp RuboCop::AST::ProcessedSource.new(File.read(File.expand_path("~/code/yarp/test.rb")), RUBY_VERSION.to_f).ast.children[0].children[1].expression'
nil
```
due to https://github.com/rubocop/rubocop-ast/blob/c1d777bd8dde3b4923c67e18b5b4ddc628da33c3/lib/rubocop/ast/node/asgn_node.rb#L20 and Array#[] out of bounds semantics.

**Comment by eregon** [comment]
How about SyntheticNode (since it's not really there syntactically) or ProvidedValueNode (a value provided at runtime, not expressible as a syntax node) for this?
cc @kddnewton

**Comment by kddnewton** [comment]
I like `ImplicitValueNode`, since it won't have anything to do with the syntax tree.

**Comment by kddnewton** [comment]
I tried implementing this tonight and it ended up being really weird. It's not really a node - you don't want to visit it, it doesn't have a location, it doesn't have any value associated with it. It doesn't have any syntax attached to it. It seems to be mostly a compilation/analysis concern. I haven't been able to figure out a way to create these nodes without allocating extra memory for what feels like very little gain.

There are a lot of places where you would potentially have this node, `foo &&= bar`, `begin; rescue foo; end`, `foo, bar, baz = qux`. In all of those places you'd have to allocate a new node, but that node wouldn't have any information associated with it.

For these reasons, I think we should mirror what the parser gem does and leave it as empty.
