### ISSUE TITLE
Should named_captures, unescape*, etc be public methods on YARP?

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1173]
https://github.com/ruby/yarp/blob/52085fddaf12290b12cde8404132718916823d40/ext/yarp/extension.c#L658-L665

I think they should not.
They seem only meant for testing but not as user-facing API.
Maybe they could be defined only `#ifdef YARP_TESTING` or so (which would only be set in this repo, not for the gem and not in CRuby), or as private methods and maybe under a `YARP::Testing` module or something.

This comes up for the Fiddle backend (https://github.com/ruby/yarp/pull/1112), it doesn't seem worth it to implement these methods for that backend if they are only meant for testing.

**Comment by kddnewton** [comment]
I definitely wouldn't implement these as part of the fiddle backend. They are meant for testing. I would probably move them under something like `YARP::Debug`. But yeah, ignore them for now.
