### ISSUE TITLE
CI is really slow on Windows

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1206]
Due to building nokogiri from source, and using ruby-head so there is no precompiled gem.
This is only visible when there is no cache though:
https://github.com/eregon/yarp/actions/runs/5772024444/job/15646682175#step:3:84
Took 11min 28s

I think we should use 3.2 to test on Windows instead of ruby-head.

**Comment by kddnewton** [comment]
I agree it's very slow, but I really want to make sure we're testing on HEAD so we don't run into any issues in 3.3.
