### ISSUE TITLE
The block argument of a call node should consistently be in CallNode#block or ArgumentsNode#block

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1310]
Right now it's there if it's a literal block:
```
$ bin/parse -e 'foo(1) {}'      
#<YARP::ParseResult:0x00007f5b82d8f830
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00007f5b82c7c970 @offsets=[0], @source="foo(1) {}">,
 @value=
  ProgramNode(0...9)(
    [],
    StatementsNode(0...9)(
      [CallNode(0...9)(
         nil,
         nil,
         (0...3),
         (3...4),
         ArgumentsNode(4...5)([IntegerNode(4...5)()]),
         (5...6),
         BlockNode(7...9)([], nil, nil, (7...8), (8...9)),
         0,
         "foo"
       )]
    )
  ),
 @warnings=[]>
```

But it's inside ArgumentsNode as the last element otherwise:
```
$ bin/parse -e 'a = ->{}; foo(1, &a)'
#<YARP::ParseResult:0x00007fb3a766f230
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00007fb3a755c9b0 @offsets=[0], @source="a = ->{}; foo(1, &a)">,
 @value=
  ProgramNode(0...20)(
    [:a],
    StatementsNode(0...20)(
      [LocalVariableWriteNode(0...8)(:a, 0, LambdaNode(4...8)([], (4...6), nil, nil), (0...1), (2...3)),
       CallNode(10...20)(
         nil,
         nil,
         (10...13),
         (13...14),
         ArgumentsNode(14...19)(
           [IntegerNode(14...15)(), BlockArgumentNode(17...19)(LocalVariableReadNode(18...19)(:a, 0), (17...18))]
         ),
         (19...20),
         nil,
         0,
         "foo"
       )]
    )
  ),
 @warnings=[]>
```

Fixing this also means CallNode#block cannot be typed as BlockNode but must be BlockNode|BlockArgumentNode (so just `Node`).

From https://github.com/ruby/yarp/pull/1243#issuecomment-1686635150

**Comment by eregon** [comment]
Alternatively, as discussed in https://github.com/ruby/yarp/pull/1243#issuecomment-1686598881, the block could be stored always in ArgumentsNode, as its own `node?` field.

**Comment by enebo** [comment]
I would like to give support to this issue.  The manipulation of having blocks and block arguments be in different locations is awkward:

```java
        if (node.block != null) {
            block = setupCallClosure(node.block);
        } else if (containsBlockArgument(node.arguments)) {
            block = args[node.arguments.arguments.length - 1];
            args = removeArg(args);
        } else {
            block = NullBlock.INSTANCE;
        }
```

This by itself may not look that bad but resizing the arg array is an expense that need not happen. The second reason for this change is we cannot examine the last element for kwargs until we do this conversion (or make logic to check 2nd to last element if last happens to be BlockArgumentNode).   I know we also have another issue open about possibly separating out kwargs from args list too but even if so then the first reason still stands.
