### ISSUE TITLE
invalid hex escapes should result in a syntax error

### ISSUE THREAD

**Issue by flavorjones** [ruby/yarp#1367]
Here's the failing test:

```ruby
  def test_invalid_hex_escape
    assert_errors expression('"\\xx"'), '"\\xx"', [
      ["Invalid hex escape.", 1..3],
    ]
  end
```

Currently this does not indicate a syntax error, and the tree is constructed using the value returned from `unescape_hexadecimal_digit` when passed `'x'`: `"\t"`

```
#<YARP::ParseResult:0x00007fa2fead0e28
 @comments=[],
 @errors=[],
 @source=#<YARP::Source:0x00007fa2fea99888 @offsets=[0], @source="\"\\xx\"">,
 @value=ProgramNode(0...5)([], StatementsNode(0...5)([StringNode(0...5)((0...1), (1...4), (4...5), "\t")])),
 @warnings=[]>
```

Ruby's behavior:

```
$ ruby -e '"\xx"'
-e:1: invalid hex escape
"\xx"
-e: compile error (SyntaxError)
```

I'm not sure what the right solution should be to propagate errors back into parser_lex for this, so I'm punting and writing this bug report.

**Comment by kddnewton** [comment]
The right way is to access the error list on the parser which is given to `yp_unescape_manipulate_string`. You'll need to pass the parser through the call tree to get it down to that function though.

**Comment by flavorjones** [comment]
Sorry I wasn't more clear -- I know I can add an error to the list, but that error seems to get recorded _twice_ -- once by `yp_unescape_calculate_difference` and once by `yp_unescape_manipulate_string`.

**Comment by kddnewton** [comment]
Oh I see. Yeah, this is part of the problem with us lazily revisiting strings. I suppose you could manually pass the error list in to `unescape` like we do with the destination buffer and pass `NULL` for calculate_difference. That might be the easiest way at the moment.

**Comment by flavorjones** [comment]
This same issue seems to be present in the unicode errors, this test asserts on it:

```ruby
  def test_do_not_allow_more_than_6_hexadecimal_digits_in_u_Unicode_character_notation
    expected = StringNode(Location(), Location(), Location(), "\u0001")

    assert_errors expected, '"\u{0000001}"', [
      ["invalid Unicode escape.", 4..11],
      ["invalid Unicode escape.", 4..11]
    ]
  end
```
