### ISSUE TITLE
Making syntax error message more consistent

### ISSUE THREAD

**Issue by flavorjones** [ruby/yarp#1379]
There are some inconsistencies in syntax error messages. The benefit of consistently formatted messages would primarily be comprehensibility, particularly for developers who do not fluently read English.

I'm happy to offer a PR to make things more consistent, but that PR would reflect my personal choices.

One alternative first step might be to **adopt a lightweight style guide**. If you're open to it, I'm happy to draft something.

Some examples of inconsistencies ...

### Capitalization

Compare

```
Unexpected ...
^

unexpected ... when parent method is not forwarding.
^
```

### Contractions

Compare

```
Can't make alias for number variables.
^^^^^

Cannot use `&&=' on a multi-write.
^^^^^^
```

### Punctuation

Compare

```
Invalid Unicode escape sequence
                               ^

Invalid Unicode escape sequence.
                               ^
```

### Quote style

Compare

```
Expected predicate expression after `until`.
                                    ^^^^^^^

Expected a predicate after 'while'
                           ^^^^^^^

Expected a predicate after `if'.
                           ^^^^

Expected index after for.
                     ^^^
```

### Use of articles

Compare

```
Expected an expression after '('.
         ^^

Expected expression after `*'.
        ^
```

### Verbosity

Compare

```
Expected to be able to parse a pattern after `|'.
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Expected to find a class name after `class`.
         ^^^^^^^^^^^^^^^^^^^^

Expected an expression after the range operator.
         ^^^^^^^^^^^^^
```

And the error message that breaks the pattern entirely:

```
Missing exponent.
```

### Other

Oxford comma?

```
Expected a bare word, symbol or global variable argument.
```

When to give actionable advice?

```
ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
```

Copyedit for clarity?

```
Unexpected else without no when clauses in case statement.
```

Are there standard terms of art that we expect all developers to know?

```
Unterminated embdoc
```

**Comment by flavorjones** [comment]
Here's my working mental model of a style guide, would love feedback.

## Message composition

When composing an error message, use sentence fragments.

Try describing the property of the code that caused the error, rather than the rule that is being
violated. It may help to use a fragment that completes a sentence beginning, "The parser
encountered (a) ...". If appropriate, add a description of the rule violation (or other helpful
context) after a semicolon.

For example:, instead of "Control escape sequence cannot be doubled", prefer:

> "Invalid control escape sequence; control cannot be repeated"

In some cases, where the failure is more general or syntax expectations are violated, it may make
more sense to use a fragment that completes a sentence beginning, "The parser ...".

For example:

> "Expected an expression after '('"
> "Cannot parse the expression"


## Message style guide

- Use articles like "a", "an", and "the" when appropriate.
  - e.g., prefer "Cannot parse the expression" to "Cannot parse expression".
- Use the common name for tokens and nodes.
  - e.g., prefer "keyword splat" to "assoc splat"
  - e.g., prefer "embedded document" to "embdoc"
- Capitalize the initial word of the message.
- Use single quotes around token literals.
- Do not use '.' or other punctuation at the end of the message.
- Do not use contractions like "can't". Prefer "cannot" to "can not".
- For tokens that can have multiple meanings, reference the token and its meaning.
  - e.g., "'\*' splat argument" is clearer and more complete than "splat argument" or "'\*' argument"

**Comment by jemmaissroff** [comment]
Thanks for doing this work, makes a lot of sense to me so far.

> When to give actionable advice?

I've been thinking a bit about this one since show and tell. It seems like this would be a really helpful feature for Ruby beginners. I'm unsure if it'd be helpful for more experienced folks, or get in the way. 

But I wonder if while you're going through the errors anyway it's worth cataloging which ones could use actionable advice? Especially since we'll build out the feature set for swapping error messages anyway, I could see how creating an "actionable advice" gem or something similar would be helpful.

**Comment by flavorjones** [comment]
> wondering if we should use the `` `*' `` syntax that CRuby seems to use when referencing source slices

@kddnewton I personally think this is the worst of all possible solutions -- mixing forward and back quotes essentially means it's unpasteable into smart formatting tools.

I agree the convention is common in the Ruby codebase, but it's not _universal_. I'd prefer `` `*` `` to the mixed version, TBH.

> cataloging which ones could use actionable advice ... creating an "actionable advice" gem or something similar would be helpful

@jemmaissroff This is a really smart idea. I may not classify/catalogue these in the first PR just to keep the scope manageable, but I would _love_ to help enable an "actionable advice" add-on for the error messages.

**Comment by kddnewton** [comment]
@flavorjones yeah that's convincing. In the case I would consistently go with backticks.
