### ISSUE TITLE
[Java] Constant pool entries as java.lang.String instead of byte[]

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#1389]
To be as correct as possible, in Loader.java, loadString() and ConstantPool#get() return `byte[]`.
However that's not really convenient to use in Java.

@enebo What type does JRuby use for local variable names, global variable names, ivar names, method names, etc?
TruffleRuby uses java.lang.String for those, at least currently.
If JRuby too, then I'll give it a shot to convert to j.l.String eagerly rather than return `byte[]`.

The annoying case is a file with BINARY encoding and non-ASCII characters.
j.l.String cannot really handle binary with non-ASCII characters.
JRuby works around that by using ISO-8859-1 (latin 1) for that case, but it's pretty confusing e.g. when looking in the debugger and requires separate data from the j.l.String to know if it's really ISO-8859-1 or BINARY.

TruffleRuby currently refuses to parse such BINARY files with non-ASCII chars, because the j.l.String used e.g. in method tables is not enough to differentiate ISO-8859-1 and BINARY on its own. It'd be nice to address that, but also low priority as it doesn't seem to cause much compatibility issues if at all.

The alternative I see is having some abstract method in Loader to customize conversion from byte[] to <T>, and <T> could be e.g. ByteList, TruffleString, java.lang.String, keep it as byte[], etc.

**Comment by eregon** [comment]
I should mention, the main advantage of dealing with this directly in Loader.java is it avoids converting multiple times the same constant pool entry, and that will then also save memory.

**Comment by enebo** [comment]
@eregon JRuby expects pretty much all of the things you listed to be eagerly made into RubySymbol (ByteList + 8859_1 String).  byte[] works well for this but if you look at JRuby's current AST you will see it all works through a name field which is RubySymbol.  eager symbols.  So better than byte[] would be RubySymbol.  

For ANY (present or future) constant pool entry they may not all be destined for symbols (how will we store strings) so I don't know how that factors into this.

Another idea we should consider is perhaps generifying this somehow.  I want RubySymbol and you want String.  The snag there would be containing implementations which can construct those in Loader but that would at least decouple things so we can both get what we want.

**Comment by eregon** [comment]
Interesting, so JRuby uses RubySymbol even for local variables, I did not expect but I should have checked https://github.com/jruby/jruby/blob/68897a4b837f2133b50d2c33efc1cf492c244d3e/core/src/main/java/org/jruby/ast/LocalVarNode.java#L44-L46.

And CRuby seems to do the same:
```
$ ruby -e 'foobarbaz = 42; p Symbol.all_symbols.grep(/foo/)'
[:foobarbaz]
```

It's kind of funny name of local variables end up as basically-permanent symbols, but why not I guess, it's a convenient way to intern local variable names and that's certainly good to do for footprint (and C doesn't have a builtin `String#intern()`). Plus it's convenient on `Binding#local_variables` of course.

OK so given RubySymbol is a JRuby-specific type we'll need the customizable conversion from byte[] (+ encoding passed somehow) to some custom type.
I'll look into that.

**Comment by enebo** [comment]
@eregon I wish I could remember why eager symbols for lvars was needed.  JRuby has other issues which did make this work out better for us (we use String for lookup to leverage intern + Java data structures but still need to resolve back to proper Symbol instance) but there was something else and I just cannot remember.

**Comment by eregon** [comment]
Thinking more about this, the type of "strings" is also in the Java type of the node fields (e.g. LocalVariableReadNode#name).
And we can't easily make those generic or it sounds pretty messy.
So I think it makes sense to solve that aspect with template-time customization, i.e., we'd set some env var like `YARP_STRING_JAVA_TYPE=String|byte[]|org.jruby.RubySymbol` during `rake templates` and we'd have the right types in generated Nodes.java and Loader.java. That also means guaranteed no overhead from generics.
I'll sketch it up when I get some time.

**Comment by enebo** [comment]
@eregon I feel like this could even be simpler with `YARP_JAVA_BACKEND=jruby|truffle`.   More granularity might help if there were more Java backends but it is just us.  Also, it means if we end up with another thing which we want to do differently we just need to hide behind that change without making another granular env var.

**Comment by enebo** [comment]
@eregon Here is a very common snippet in JRuby right now:

```java
    private Operand buildGlobalVariableRead(Variable result, GlobalVariableReadNode node) {
        return buildGlobalVar(result, symbol(node.name));
    }
```

So `node.getName()` which returns RubySymbol would be helpful.  I think this would be String for TR and it would make proper encoded string.

Side-note here is a case where both old and new parser shares the IR common method to build a global variable.  I was mentioning why I was ok with common methods (this being a significant reason).

**Comment by eregon** [comment]
> @eregon I feel like this could even be simpler with `YARP_JAVA_BACKEND=jruby|truffle`. More granularity might help if there were more Java backends but it is just us. Also, it means if we end up with another thing which we want to do differently we just need to hide behind that change without making another granular env var.

That makes a lot of sense, I'll do that.
