### ISSUE TITLE
YP_REGULAR_EXPRESSION_FLAGS_* do not match ONIGMO values

### ISSUE THREAD

**Issue by enebo** [ruby/yarp#1425]
JRuby and MRI both use the same integer values for regexp flags. The ones YARP uses are not the same.  It is simpler to pass in this single flag value straight through rather than translate the value from one number system to another.

joni source:

```java
    int RE_OPTION_NONE         = 0;
    int RE_OPTION_IGNORECASE   = 1;
    int RE_OPTION_EXTENDED     = 2;
    int RE_OPTION_MULTILINE    = 4;
    int RE_OPTION_SINGLELINE   = 8;
    int RE_OPTION_POSIXLINE    = (RE_OPTION_MULTILINE | RE_OPTION_SINGLELINE);
    int RE_FIXED               = 16;
    int RE_NONE                = 32;
    int RE_UNICODE             = 64;
    int RE_OPTION_ONCE         = 128; // odd...but it is odd in ruby too.  
```

onigmo

```C
#define ONIG_OPTION_NONE                 0U
#define ONIG_OPTION_IGNORECASE           1U
#define ONIG_OPTION_EXTEND               (ONIG_OPTION_IGNORECASE         << 1)
#define ONIG_OPTION_MULTILINE            (ONIG_OPTION_EXTEND             << 1)
#define ONIG_OPTION_SINGLELINE           (ONIG_OPTION_MULTILINE          << 1)
```

yarp

```C
typedef enum {
    YP_REGULAR_EXPRESSION_FLAGS_IGNORE_CASE = 1 << 1,
    YP_REGULAR_EXPRESSION_FLAGS_MULTI_LINE = 1 << 2,
    YP_REGULAR_EXPRESSION_FLAGS_EXTENDED = 1 << 3,
    YP_REGULAR_EXPRESSION_FLAGS_EUC_JP = 1 << 4,
    YP_REGULAR_EXPRESSION_FLAGS_ASCII_8BIT = 1 << 5,
    YP_REGULAR_EXPRESSION_FLAGS_WINDOWS_31J = 1 << 6,
    YP_REGULAR_EXPRESSION_FLAGS_UTF_8 = 1 << 7,
    YP_REGULAR_EXPRESSION_FLAGS_ONCE = 1 << 8,
} yp_regular_expression_flags_t;

```

**Comment by kddnewton** [comment]
From what I can tell, the options boil down to:

```
65536 'o' RE_OPTION_ONCE
    1 'i' ONIG_OPTION_IGNORECASE
    2 'x' ONIG_OPTION_EXTEND
    4 'm' ONIG_OPTION_MULTILINE
   32 'n' ARG_ENCODING_NONE
25882 'e' ARG_ENCODING_FIXED | ENCINDEX_EUC_JP | ('e' << RE_OPTION_ENCODING_SHIFT)
29467 's' ARG_ENCODING_FIXED | ENCINDEX_Windows_31J | ('s' << RE_OPTION_ENCODING_SHIFT)
29969 'u' ARG_ENCODING_FIXED | rb_utf8_encindex() | ('u' << RE_OPTION_ENCODING_SHIFT)
```

which options were you thinking you wanted to line up? If I flip `MULTI_LINE` and `EXTENDED` at least those values would line up with a single right shift. The reason they start at 2 is because all of the nodes have a common line flag bit set.

For `SINGLELINE`, is that always set if `MULTILINE` is not set?

**Comment by enebo** [comment]
@kddnewton those two values flipped would make things work.  In Loader we should probably just shift to get onigmo value.  It would feel weird to do that in IR building.

As far as other values I did not really look too closely past looking up the source itself.   I just started and things were off by a power of 2 then shifted and then got multiline instead of extended.  The I fired up the issue tracker :smile:

**Comment by enebo** [comment]
A number of these values are also exposed as constants in Regexp.  Not important past looking up what their numeric value is using Ruby.

**Comment by kddnewton** [comment]
Fixed by https://github.com/ruby/yarp/pull/1437.

@enebo I added some convenience methods to the Ruby API, but I wasn't sure if you wanted that in the Java side as well. You can see it here: https://github.com/ruby/yarp/pull/1438. We haven't been mirroring these in the Java side yet, but I'm happy to support it if you want it.

**Comment by enebo** [comment]
@kddnewton masking to just return the onigo/joni real value is perfect.  Nicer than manually doing it.

**Comment by eregon** [comment]
@enebo Note that when serializing there is already https://github.com/ruby/yarp/blob/63eda4c7a64a299394ffb39796021e66ebc92929/templates/src/serialize.c.erb#L109 so when deserialized it should be the right values without needing to shift anything.

i.e. this 1-bit shift should be invisible both to Java but also Ruby, it only exists in C.

**Comment by eregon** [comment]
So now with the reorder the first 3 flags line up in YARP:
```java
    public static final class RegularExpressionFlags implements Comparable<RegularExpressionFlags> {

        // i - ignores the case of characters when matching
        public static final short IGNORE_CASE = 1 << 0;

        // x - ignores whitespace and allows comments in regular expressions
        public static final short EXTENDED = 1 << 1;

        // m - allows $ to match the end of lines within strings
        public static final short MULTI_LINE = 1 << 2;
```

**Comment by enebo** [comment]
@eregon someone else corrected the order yesterday and the flag value seems correct now.   Maybe I was wrong by the off-by-2 issue?
