### ISSUE TITLE
Make implicit return explicit

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/yarp#1431]
Consider these two programs:

```
def foo
  1
end
```

```
def foo
  return 1
end
```

The first AST will not have a `ReturnNode` and the second one will.

The compiler needs to add a `leave` instruction on `ReturnNodes` in case they're an early return. But due to the first case, the compiler also adds a `leave` instruction at the end of the method body.

That means that in the second case, as the compiler currently works, we get an extra `leave` instruction. The most obvious solution for the compiler is to check if there's a `ReturnNode` embedded within the final node of the body (could be within an `IfNode` for example). But this seems a little counterintuitive to me.

I think a better approach would be for YARP to wrap the final instruction in a method in a `ReturnNode` so that the trees for the two equivalent methods above match.

**Comment by mbj** [comment]
Optimization is the job of the compiler. Its job is to represent concrete syntax lossless to for tool consumption. And whats considered redundant by one tool (compiler) is not redundant to other tools (linters) and vice versa. Its the nature of a good AST that it can be used for many use cases not just "unidirectional" for compiler usages.

As the author of tools that are very sensitive to these kinds of differences: Please fix the compiler to do its job even if it appears to be counter intuitive. Parsers should not pre-evaluate the language in any way.

**Comment by seven1m** [comment]
I agree the AST should represent the code that was written. Otherwise it would be impossible to write a code formatter with YARP as the parser.

**Comment by kddnewton** [comment]
I think this would be difficult in situations like:

```ruby
def foo
  if bar
    return baz
  else
    qux
  end
end
```

In general if we were to put a return on the last statement, then it would probably be around the entire if statement here, which would be difficult since one of the clauses has an explicit return and the other doesn't. If we were to instead attempt to insert it into every clause, we would have to rewalk the tree and effectively implement our own compiler.

**Comment by jemmaissroff** [comment]
Thanks for the enthusiasm around YARP @mbj. What I'm suggesting here is lossless. 

We have existing patterns in YARP for using the same node type for cases of syntactic sugar (`IfNode` for example). The lack of an explicit return on the final statement of a method is syntactic sugar for actually having an explicit return. Concretely, there is no difference programmatically in whether the node returns a value or not. And I can think of plenty of tools that would benefit from knowing exactly which nodes returned values (some type checkers, for example), that aren't just the compiler. Although in cases like the `IfNode` the pure sublocations are enough, we could also add a flag to signify if it's explicit or implicit, or so something like make an entire new node type `ImplicitReturn`.

I'm not sure I follow your example of `1+1` exactly, because it's not necessarily 2 in Ruby. But what I think you're getting at is that (beyond no guarantee of correctness) you would lose information by making it 2. I'm not suggesting any loss of information, just suggesting that syntactic sugar for a return get presented as such.

**Comment by jemmaissroff** [comment]
> In general if we were to put a return on the last statement, then it would probably be around the entire if statement here, which would be difficult since one of the clauses has an explicit return and the other doesn't. If we were to instead attempt to insert it into every clause, we would have to rewalk the tree and effectively implement our own compiler.

@kddnewton this point is compelling to me. The only slight pushback I'd have is to wrap it all in an `ImplicitReturn`, but I think that wrapper wouldn't be worth the memory overhead. Going to close the issue, I'll investigate using `popped` to solve this instead.
