### ISSUE TITLE
AliasGlobalVariableNode does not need child nodes.

### ISSUE THREAD

**Issue by enebo** [ruby/yarp#1480]
It can only be global variables so this should just be String for old_name and new_name.

**Comment by enebo** [comment]
I spoke too soon.  They can include BackReferenceReadNode but at the end of the day isn't this still just required to be a name?

**Comment by kddnewton** [comment]
This one I definitely want to keep as is. It could be a back reference, a numbered reference, a global read, or a missing node in the case of a syntax error. The numbered references have integers on them whereas others have constant names.

**Comment by enebo** [comment]
@kddnewton ok.  I will just make a switch to extract the name from the possible types then.

**Comment by eregon** [comment]
I think the global variable name in this case can be extracted by just using the location startOffset and length (then no need to switch).

**Comment by enebo** [comment]
@eregon yeah that should work.  From a future-proof perspective (consider aspirational comments in other issue on not having source) we should make INameNode or something like that.  Then we can access the name fields?  Getting name from a node seems to be a pretty common activity.

**Comment by eregon** [comment]
Right, I was also thinking about some interface to get the name.
One issue here is e.g. `BackReferenceReadNode` doesn't have a `name` field (it's always `$'` so fair enough I guess).
So we'd need some special case for some of these nodes to implement a `name()` method.

**Comment by eregon** [comment]
I edited my previous comment, `BackReferenceReadNode` is not always `$'`.
I think the best fix here would be to add such an interface for the name, but first add a `constant name` field to BackReferenceReadNode and other gvar read nodes.
Then it would just work without needing to access the source once we serialize all entries of the constant pool as embedded/owned (and not referring to source).

**Comment by enebo** [comment]
> I edited my previous comment, `BackReferenceReadNode` is not always `$'`. I think the best fix here would be to add such an interface for the name, but first add a `constant name` field to BackReferenceReadNode and other gvar read nodes. Then it would just work without needing to access the source once we serialize all entries of the constant pool as embedded/owned (and not referring to source).

I think this fits with future goals in removing needing offsets to access source data + moves name-like stuff to having name fields.

@kddnewton would it be reasonable to put all four BackReference variable names into the comment field in config.yml?  The more I can read that file and the less I have to search in yarp.c the better.

**Comment by kddnewton** [comment]
Yeah that's fine. I'm also happy to add a name field to backreferencereadnode, it makes sense that that would be in the pool as well.
