### ISSUE TITLE
RegexpNode options for e, u, s, and n don't match MRI

### ISSUE THREAD

**Issue by seven1m** [ruby/yarp#1516]
We got `m`, `i`, and `x` working in #1437, but the other four require a bit more care. `e`. `u`, and `s` map to a single bit, and `n` is high enough that masking alone won't work.

What I'd like to see:

```ruby
irb(main):001:0> //e.options
=> 16
irb(main):002:0> //u.options
=> 16
irb(main):003:0> //s.options
=> 16
irb(main):004:0> Regexp::FIXEDENCODING
=> 16
irb(main):005:0> //n.options
=> 32
irb(main):006:0> Regexp::NOENCODING
=> 32
```

What YARP gives:

```ruby
irb(main):007:0> YARP.parse('//e').value.statements.body.first.options
=> 0
irb(main):008:0> YARP.parse('//u').value.statements.body.first.options
=> 0
irb(main):009:0> YARP.parse('//s').value.statements.body.first.options
=> 0
irb(main):010:0> YARP.parse('//n').value.statements.body.first.options
=> 0
```

**Comment by eregon** [comment]
I'm curious, do you use the YARP Ruby API in Natalie?
How does that work? Does it run on Natalie and using another Ruby parser then?
Or it runs on CRuby and then is somehow transferred to Natalie? (if so serialization might be a better fit)

Or maybe this is simply for another purpose than Natalie?

**Comment by seven1m** [comment]
The Natalie compiler is itself written in Ruby, so we need MRI to bootstrap. Self-hosted Natalie is kinda broken right now, but the idea is that the MRI-hosted Natalie compiler can compile the compiler, at which point we'll use the YARP C library in self-hosted Natalie. I haven't really thought through how that's going to work yet.

We use NatalieParser as both a gem-with-c-extension *and* as a C++ library (depending on hosting mode), so I was hoping YARP could work the same way.

**Comment by eregon** [comment]
> the idea is that the MRI-hosted Natalie compiler can compile the compiler, at which point we'll use the YARP C library in self-hosted Natalie.

Oh, right! So the Natalie compiler can handle parsing with either Ruby or C/C++ nodes then, impressive.
Of course API like RegularExpressionNode#options is currently only available in Ruby, but could be added for C and/or Java too.
