### ISSUE TITLE
Node location testing

### ISSUE THREAD

**Issue by kddnewton** [ruby/yarp#434]
We have some nodes tested for their location information in `location_test.rb`. We need all of our nodes to be tested for their location information (spoiler: a lot of them are wrong at the moment when they contain lists of nodes).

**Comment by eregon** [comment]
Quite a few nodes are also missing location information, with https://github.com/Shopify/yarp/pull/462 it's now easy to see which ones.
For example:
```
$ bundle exec ruby -Ilib -ryarp -e 'pp YARP.parse("-> { 1 }")'
#<YARP::ParseResult:0x00007f8deab1dc10
 @comments=[],
 @errors=[],
 @value=
  Program(?..6)(
    Scope(?..?)([]),
    Statements(?..6)(
      [LambdaNode(?..6)(
         Scope(?..?)([]),
         nil,
         BlockVarNode(?..?)(ParametersNode(?..?)([], [], nil, [], nil, nil), []),
         nil,
         Statements(5..6)([IntegerNode(5..6)()])
       )]
    )
  ),
 @warnings=[]>
```

**Comment by kddnewton** [comment]
Remaining files to test:

- [ ] CapturePatternNode
- [ ] ClassNode
- [ ] ConstantPathWriteNode
- [ ] DefNode
- [ ] DefinedNode
- [ ] ElseNode
- [ ] EnsureNode
- [ ] FindPatternNode
- [ ] GlobalVariableReadNode
- [ ] GlobalVariableWriteNode
- [ ] HashPatternNode
- [ ] InNode
- [ ] KeywordParameterNode
- [ ] KeywordRestParameterNode
- [ ] LambdaNode
- [ ] LocalVariableReadNode
- [ ] LocalVariableWriteNode
- [ ] MatchPredicateNode
- [ ] MatchRequiredNode
- [ ] MissingNode
- [ ] ModuleNode
- [ ] MultiWriteNode
- [ ] OperatorAssignmentNode
- [ ] OptionalParameterNode
- [ ] ParametersNode
- [ ] PinnedExpressionNode
- [ ] PinnedVariableNode
- [ ] ProgramNode
- [ ] RegularExpressionNode
- [ ] RequiredDestructuredParameterNode
- [ ] RequiredParameterNode
- [ ] RescueModifierNode
- [ ] RestParameterNode
- [ ] ReturnNode
- [ ] SingletonClassNode
- [ ] SplatNode
- [ ] StringConcatNode
- [ ] StringInterpolatedNode
- [ ] StringNode
- [ ] SymbolNode
- [ ] UnlessNode
- [ ] WhenNode
- [ ] YieldNode
