### ISSUE TITLE
Serialization needs encoding

### ISSUE THREAD

**Issue by kddnewton** [ruby/yarp#643]
When we serialize to a binary string, we should put in the encoding as well. This should be an enum that the deserializers can understand. Right now when we deserialize in Ruby we just force it into UTF-8, which is definitely not correct.

**Comment by enebo** [comment]
In talking to Kevin last week (not trying to ping him during his leave) we talked about putting errors, encoding, and other potentially global info (pragmas?) in the header of the serialized file (I presume right after the version check).
