### ISSUE TITLE
Regexp Node should encode options

### ISSUE THREAD

**Issue by enebo** [ruby/yarp#760]
Given ```/foo/i``` the current node structure is:

```text
#<YARP::ParseResult:0x00007f95a1ade6a0
 @comments=[],
 @errors=[],
 @value=
  ProgramNode(0...6)(
    ScopeNode(0...0)([]),
    StatementsNode(0...6)(
      [RegularExpressionNode(0...6)(
         REGEXP_BEGIN(0...1)("/"),
         STRING_CONTENT(1...4)("foo"),
         REGEXP_END(4...6)("/i"),
         "foo"
       )]
    )
  ),
 @warnings=[]>
```

In order to determine what options exist consumers need to make a string processing method for REGEXP_END (execution will likely end up stripping syntax fields out of nodes at some point).  I talked last week to @kddnewton about allowing node types to have enums defined.  This may be a good target node to try that on.

**Comment by eregon** [comment]
Maybe a string of options is simpler here and actually more compact?
A single enum value wouldn't be enough here, we'd need an enum set and that doesn't seem any smaller than a string for these 1-letter options. Plus if we deduplicate strings we can save even more.

**Comment by enebo** [comment]
@eregon I think I misspoke on it being an enum because it would have to be a set as you say.  I did make a method for parsing a string and making a direct object so that definitely works (but I still do not want to read the token field for it.  

A second idea is to use the standard flag values that both oniguruma and joni support (e.g. flags like ONIG_OPTION_MULTILINE/RE_OPTION_MULTILINE).  This would allow us to encode the options as a single numerical value saving space (and we probably both have methods which can process these values).

**Comment by enebo** [comment]
This is needed for #807
