### ISSUE TITLE
YARP.load improvements

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/yarp#765]
* Document `YARP.load`. Docs should live in `doc/extension.md` with the `YARP.dump` documentation
* Add a line in `doc/serialization.md` pointing to more serialization methods that are documented in `doc/extension.md` - makes it easier to find all of the serialization docs 
* Extract hardcoded version heading to one place, instead of duplicating it [here](https://github.com/Shopify/yarp/blob/main/bin/templates/lib/yarp/serialize.rb.erb#L21-L23) and [here](https://github.com/Shopify/yarp/blob/036e0b60fa35f9bba89ef8ecb001ff1d9a050a2c/src/yarp.c#L11573-L11576)

**Comment by kddnewton** [comment]
I think this is now all documented thanks to @eregon's FFI backend work.

**Comment by eregon** [comment]
Right, except this cleanup:

> * Extract hardcoded version heading to one place, instead of duplicating it [here](https://github.com/Shopify/yarp/blob/main/bin/templates/lib/yarp/serialize.rb.erb#L21-L23) and [here](https://github.com/Shopify/yarp/blob/036e0b60fa35f9bba89ef8ecb001ff1d9a050a2c/src/yarp.c#L11573-L11576)

I think we should use the templates to fill the version, so it's not duplicated in so many places.
