### ISSUE TITLE
Parsing will store line

### ISSUE THREAD

**Issue by enebo** [ruby/yarp#808]
compile.c uses line for every insn created and parsing already needs to calculate line for syntax errors while parsing.  Serialization desires having line number (for JRuby at least).

In both cases the tradeoff is storing an int vs generating newline lookup table.

**Comment by eregon** [comment]
As discussed on the call, it sounds fine to store the line number in serialized form too for now, and later optimize it for TruffleRuby where it's most likely not necessary to have the line there.

**Comment by enebo** [comment]
@eregon yeah this is part of what I was trying to say about how impls may want to do some things differently.  It makes total sense that TR would not want line number if it is using offsets.

**Comment by kddnewton** [comment]
I'm going to close this to consolidate on #775
