### ISSUE TITLE
Include rubylexer tests.

### ISSUE THREAD

**Issue by HParker** [ruby/yarp#839]
https://github.com/coatl/rubylexer

The gem is very old, but I suspect all / most of the tests are still valuable and accurate.

**Comment by kddnewton** [comment]
@HParker do you have time to come back to this? I'd be very interested in having these tests in the repo.

**Comment by kddnewton** [comment]
Actually @HParker nevermind. I just read through the license on it and I don't think we can import the tests. They'd be useful to run in case we have crashes potentially. https://github.com/coatl/rubylexer/blob/master/COPYING
