### ISSUE TITLE
Store startOffset + length instead of startOffset + endOffset

### ISSUE THREAD

**Issue by eregon** [ruby/yarp#872]
From https://github.com/Shopify/yarp/discussions/741#discussioncomment-5482693

Doing so is simply better for the serialized size, because length is always <= endOffset, and often much smaller.

I think it might make sense to change it everywhere, but we could also just change it for serialization.
@jemmaissroff WDYT?

**Comment by eregon** [comment]
Now that https://github.com/ruby/yarp/pull/873 is merged, I think we should change it for Java Nodes and Ruby Locations, because that avoids extra work like https://github.com/ruby/yarp/pull/873#discussion_r1169890089 and also some places need to recompute the length from end_offset - start_offset which feels inefficient.

I'm not sure about C nodes structs though, WDYT @jemmaissroff ?
That's probably a lot more involved to change, so if we do that, I think best to do it separately.

**Comment by eregon** [comment]
@jemmaissroff Should we change it for C structs too? How do we do that without having huge conflicts?

**Comment by eregon** [comment]
I gave it a shot at https://github.com/ruby/yarp/compare/main...eregon:yarp:c-struct-length, that compiles but many offsets are wrong, there must be some mistranslation.
Given the frequent usage of `end` while computing location in `yarp.c`, I think it might be best to just keep it as-is, it's far more convenient.

**Comment by kddnewton** [comment]
This works in the serialization, but I think it would not be worth it in the actual library. I'm going to close this now that we have it in the serialization.
