### ISSUE TITLE
Assert child node's location is non-overlapping for known nodes

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/yarp#892]
We have some cases where it's acceptable for a child node's location to be non overlapping with its parent, and others where the child node's location needs to be strictly within its parent's location. 

Our test suite should check if child nodes' locations are within parent's nodes' locations, and if not, categorize the node type

**Comment by jemmaissroff** [comment]
Started looking at this, fixed some cases, have [this branch](https://github.com/ruby/yarp/tree/parse-test) as a test branch now. It asserts that locations are non-overlapping. It notably ignores `StringInterpolatedNodes` because of Heredocs.

It has also generated this set of files that currently still have overlapping locations:
- [ ] test/fixtures/classes.txt
- [ ] test/fixtures/if.txt
- [ ] test/fixtures/method_calls.txt
- [ ] test/fixtures/methods.txt
- [ ] test/fixtures/modules.txt
- [ ] test/fixtures/procs.txt
- [ ] test/fixtures/rescue.txt
- [ ] test/fixtures/seattlerb/attr_asgn_colon_id.txt
- [ ] test/fixtures/seattlerb/attrasgn_primary_dot_constant.txt
- [ ] test/fixtures/seattlerb/case_in_42.txt
- [ ] test/fixtures/seattlerb/case_in_42_2.txt
- [ ] test/fixtures/seattlerb/case_in_67.txt
- [ ] test/fixtures/seattlerb/case_in_86.txt
- [ ] test/fixtures/seattlerb/case_in_86_2.txt
- [ ] test/fixtures/seattlerb/case_in_hash_pat.txt
- [ ] test/fixtures/seattlerb/case_in_hash_pat_assign.txt
- [ ] test/fixtures/seattlerb/case_in_hash_pat_paren_true.txt
- [ ] test/fixtures/seattlerb/case_in_hash_pat_rest.txt
- [ ] test/fixtures/seattlerb/case_in_hash_pat_rest_solo.txt
- [ ] test/fixtures/seattlerb/defn_oneliner_rescue.txt
- [ ] test/fixtures/seattlerb/defs_oneliner_rescue.txt
- [ ] test/fixtures/seattlerb/rescue_do_end_ensure_result.txt
- [ ] test/fixtures/seattlerb/rescue_do_end_no_raise.txt
- [ ] test/fixtures/seattlerb/rescue_do_end_raised.txt
- [ ] test/fixtures/seattlerb/rescue_do_end_rescued.txt
- [ ] test/fixtures/seattlerb/safe_attrasgn.txt
- [ ] test/fixtures/seattlerb/safe_attrasgn_constant.txt
- [ ] test/fixtures/symbols.txt
- [ ] test/fixtures/unparser/corpus/literal/assignment.txt
- [ ] test/fixtures/unparser/corpus/literal/block.txt
- [ ] test/fixtures/unparser/corpus/literal/case.txt
- [ ] test/fixtures/unparser/corpus/literal/def.txt
- [ ] test/fixtures/unparser/corpus/literal/dstr.txt
- [ ] test/fixtures/unparser/corpus/literal/literal.txt
- [ ] test/fixtures/unparser/corpus/literal/pattern.txt
- [ ] test/fixtures/unparser/corpus/literal/send.txt
- [ ] test/fixtures/whitequark/array_symbols_interp.txt
- [ ] test/fixtures/whitequark/if_elsif.txt
- [ ] test/fixtures/whitequark/rescue_without_begin_end.txt
- [ ] test/fixtures/whitequark/send_attr_asgn.txt
- [ ] test/fixtures/whitequark/send_attr_asgn_conditional.txt

**Comment by jemmaissroff** [comment]
cc @haldun  - figured this might be interesting to you

**Comment by eregon** [comment]
Agreed, I think that makes. It's a bit like __FILE__ or DATA.read, they sort of are string literals but the contents isn't at the same place as the usage.
