### ISSUE TITLE
Add Windows Build

### ISSUE THREAD

**Issue by jemmaissroff** [ruby/yarp#980]
We should have a Windows build on GitHub Actions that runs YARP against a Windows machine

**Comment by jemmaissroff** [comment]
@MSP-greg - any chance you could take a look at this?

**Comment by MSP-Greg** [comment]
@jemmaissroff

Yes, I'll check this weekend.  I don't consider myself a strong c coder, so I'm not sure if I can find the cause of the SEGV.

As I mentioned, I believe on Windows we need to load the `librubyparser.dll` file with Fiddle, although compiling it all together might be an option?

**Comment by jemmaissroff** [comment]
I can find the SEGV / debug it (or pair with you!). 

The part that would be very helpful is getting the build itself running. Currently to debug Windows issues, I push to ruby/ruby CI which is a slow dev cycle. Would be much easier to be able to do it on YARP's GitHub actions directly!

**Comment by MSP-Greg** [comment]
> I push to ruby/ruby CI which is a slow dev cycle

I looked at the build linked to in #985.  I don't know how familiar you are with Ruby Windows (or Windows).  The build shown is a 'mswin' build, which uses MSFT's Visual C (MSVC).  There's a Ruby master build available on GitHub Actions that's mswin, but for the most part, most people use 'mingw' builds, which for current versions use the MSYS2 UCRT64 gcc tool chain.

Anyway, I was using MSYS2 UCRT64 and Ruby master when I worked on it.  GitHub Actions can be set up to test both...

**Comment by flavorjones** [comment]
:disappointed: I had been working on this. I'll try to merge my work with @MSP-Greg's.

**Comment by MSP-Greg** [comment]
@flavorjones

Thanks.  Feel free to take from my code.  From your comment in PR #1000, "introduce static linking of the ruby C extension."

That sounds like a lot more code than my PR, along with fixing the compile errors...  I can certainly help with and Actions issues, but you're certainly familiar with those...

Also, some recent changes to extconf.rb & Rakefile may affect making this a gem, Not.sure.
